@startuml

PaanDAO ..> TimeTable
PaanDAO ..> TaskFactory

class PaanDAO{
- cnn : Connection
- st : Statement
- rs : ResultSet
- connect() : void
+ checkExist(String tableName) : boolean
+ checkDataExist(String tableName) : boolean
+ createTable(String tableName) : void
+ clearDailyTask() : void
+  insert(int theme, int timeFormat) : void
+ insert(int drink,Date date)  : void
+ insert(String table,String detail,Date date) : void
+ insert(String table, String detail) : void
+ updateSettings(String type, int val) : void
+ update(String table, String detail, Date date) : void
+ updateDaily(int val) : void
+ updateDaily(Date newDate) : void
+ updateTodo(String table,int status, String detail) : void
+ loadSettings(String type) : int
+ loadTimeline() : LinkedList<TaskEvent>
+ loadTodoList(String tableName) : TodoList
+ loadDrink() : int
+ loadMood(Date date) : TaskEvent
+ loadEvent(Date date) : EventList
+ loadTimeTable() : TimeTable
+ remove(String detail, Date delDate) : void
+ remove(String table,int rowId) : void
+ remove(Table table) : void
+ getResetDate() : Date
+ getRowID(String table, int index) : int
}
@enduml