/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import static project_ui.DailyForm.font;

/**
 *
 * @author faynch
 */
public class DailyTask extends javax.swing.JPanel {
    static Font font;
    static Color bgColor;
    static Color fgColor;

    /**
     * Creates new form dailyTask
     */
    public DailyTask() {
        
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, new File("Chewy-Regular.ttf")).deriveFont(20f);
            GraphicsEnvironment g = GraphicsEnvironment.getLocalGraphicsEnvironment();
            g.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("Chewy-Regular.ttf")));
        }
        catch(IOException | FontFormatException e){
            
        }     
        
        initComponents();
        
        this.setBackground(bgColor);
    }

    public JToggleButton getDone() {
        return done;
    }
    
    public static void updateTheme() {
        taskName.setBackground(bgColor);
        taskName.setForeground(fgColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        done = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taskName = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(550, 50));
        setMinimumSize(new java.awt.Dimension(550, 50));
        setPreferredSize(new java.awt.Dimension(550, 50));

        done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incomplete.png"))); // NOI18N
        done.setBorderPainted(false);
        done.setContentAreaFilled(false);
        done.setFocusPainted(false);
        done.setFocusable(false);
        done.setMargin(new java.awt.Insets(0, 0, 0, 0));
        done.setMaximumSize(new java.awt.Dimension(50, 50));
        done.setMinimumSize(new java.awt.Dimension(50, 50));
        done.setPreferredSize(new java.awt.Dimension(50, 50));
        done.setSize(new java.awt.Dimension(50, 50));
        done.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                doneItemStateChanged(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(494, 50));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(494, 50));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(494, 50));
        jScrollPane1.setSize(new java.awt.Dimension(494, 50));

        taskName.setFont(font);
        taskName.setBorder(null);
        taskName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(taskName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(done, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doneItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_doneItemStateChanged
        // TODO add your handling code here:
        if (done.isSelected()) {
            done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/complete.png")));
        }
        else {
            done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/incomplete.png")));
        }
    }//GEN-LAST:event_doneItemStateChanged

    private void taskNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_taskNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton done;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextField taskName;
    // End of variables declaration//GEN-END:variables
}
