/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author faynch
 */
public class memoForm extends javax.swing.JFrame {
    Font font;
    static Color bgColor;
    static Color fgColor;

    /**
     * Creates new form memoForm
     */
    public memoForm() {
        
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, new File("Chewy-Regular.ttf")).deriveFont(30f);
            GraphicsEnvironment g = GraphicsEnvironment.getLocalGraphicsEnvironment();
            g.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("Chewy-Regular.ttf")));
        }
        catch(IOException | FontFormatException e){
            
        }
        
        initComponents();
//        leftB.setOpaque(false);
        leftB.setContentAreaFilled(false);
        leftB.setBorderPainted(false);
        rightB.setContentAreaFilled(false);
        rightB.setBorderPainted(false);
        dateL.setFont(font.deriveFont(40f));
        
        updateTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moodButtonGroup = new javax.swing.ButtonGroup();
        memoP = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        todolistP = new javax.swing.JPanel();
        todolistL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        todolistT = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateP = new javax.swing.JPanel();
        leftB = new javax.swing.JButton();
        rightB = new javax.swing.JButton();
        dateL = new javax.swing.JLabel();
        eventP = new javax.swing.JPanel();
        eventL = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        eventT = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        moodP = new javax.swing.JPanel();
        moodL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setResizable(false);

        memoP.setBackground(new java.awt.Color(255, 255, 255));
        memoP.setMaximumSize(new java.awt.Dimension(1100, 700));
        memoP.setMinimumSize(new java.awt.Dimension(1100, 700));
        memoP.setPreferredSize(new java.awt.Dimension(1100, 700));

        backButton.setText("jButton1");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        todolistP.setBackground(new java.awt.Color(255, 255, 255));
        todolistP.setPreferredSize(new java.awt.Dimension(500, 500));

        todolistL.setFont(font);
        todolistL.setText("TO DO LIST");

        todolistT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(todolistT);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout todolistPLayout = new javax.swing.GroupLayout(todolistP);
        todolistP.setLayout(todolistPLayout);
        todolistPLayout.setHorizontalGroup(
            todolistPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGroup(todolistPLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(todolistL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(todolistPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );
        todolistPLayout.setVerticalGroup(
            todolistPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(todolistPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todolistL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(todolistPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        dateP.setBackground(new java.awt.Color(255, 255, 255));

        leftB.setBackground(new java.awt.Color(255, 255, 255));
        leftB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_ui/leftB.png"))); // NOI18N
        leftB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftBActionPerformed(evt);
            }
        });

        rightB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_ui/rightB.png"))); // NOI18N

        dateL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateL.setText("MON 23 OCT");
        dateL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dateL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout datePLayout = new javax.swing.GroupLayout(dateP);
        dateP.setLayout(datePLayout);
        datePLayout.setHorizontalGroup(
            datePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(leftB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dateL, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rightB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        datePLayout.setVerticalGroup(
            datePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datePLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightB, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(leftB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        eventP.setBackground(new java.awt.Color(255, 255, 255));

        eventL.setFont(font);
        eventL.setText("EVENT");

        jScrollPane3.setViewportView(eventT);

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout eventPLayout = new javax.swing.GroupLayout(eventP);
        eventP.setLayout(eventPLayout);
        eventPLayout.setHorizontalGroup(
            eventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(eventPLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(eventL)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(eventPLayout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
        );
        eventPLayout.setVerticalGroup(
            eventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventPLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(eventL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(eventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        moodP.setBackground(new java.awt.Color(255, 255, 255));

        moodL.setBackground(new java.awt.Color(255, 255, 255));
        moodL.setFont(font);
        moodL.setText("MOOD");

        javax.swing.GroupLayout moodPLayout = new javax.swing.GroupLayout(moodP);
        moodP.setLayout(moodPLayout);
        moodPLayout.setHorizontalGroup(
            moodPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moodPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(moodL)
                .addContainerGap(413, Short.MAX_VALUE))
        );
        moodPLayout.setVerticalGroup(
            moodPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moodPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(moodL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout memoPLayout = new javax.swing.GroupLayout(memoP);
        memoP.setLayout(memoPLayout);
        memoPLayout.setHorizontalGroup(
            memoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoPLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(memoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memoPLayout.createSequentialGroup()
                        .addComponent(backButton)
                        .addContainerGap())
                    .addGroup(memoPLayout.createSequentialGroup()
                        .addComponent(todolistP, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(memoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memoPLayout.createSequentialGroup()
                                .addComponent(dateP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(memoPLayout.createSequentialGroup()
                                .addGroup(memoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(moodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eventP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        memoPLayout.setVerticalGroup(
            memoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memoPLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(memoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(todolistP, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(memoPLayout.createSequentialGroup()
                        .addComponent(dateP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moodP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new mainWindow().setVisible(true);
        mainWindow.bgColor = bgColor;
        mainWindow.fgColor = fgColor;
        mainWindow.updateTheme();
    }//GEN-LAST:event_backButtonActionPerformed

    private void leftBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memoForm().setVisible(true);
            }
        });
    }
    
    public static void updateTheme() {
        memoP.setBackground(bgColor);
        todolistP.setBackground(bgColor);
        todolistT.setBackground(bgColor);
        dateP.setBackground(bgColor);
        dateL.setBackground(bgColor);
        eventP.setBackground(bgColor);
        eventL.setBackground(bgColor);
        eventT.setBackground(bgColor);
        moodP.setBackground(bgColor);
        moodL.setBackground(bgColor);
       
        
        todolistL.setForeground(fgColor);
        todolistT.setForeground(fgColor);
        dateL.setForeground(fgColor);
        eventL.setForeground(fgColor);
        eventT.setForeground(fgColor);
        moodL.setForeground(fgColor);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private static javax.swing.JLabel dateL;
    private static javax.swing.JPanel dateP;
    private static javax.swing.JLabel eventL;
    private static javax.swing.JPanel eventP;
    private static javax.swing.JList<String> eventT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton leftB;
    private static javax.swing.JPanel memoP;
    private javax.swing.ButtonGroup moodButtonGroup;
    private static javax.swing.JLabel moodL;
    private static javax.swing.JPanel moodP;
    private javax.swing.JButton rightB;
    private static javax.swing.JLabel todolistL;
    private static javax.swing.JPanel todolistP;
    private static javax.swing.JTable todolistT;
    // End of variables declaration//GEN-END:variables
}
