/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import static project_ui.mainWindow.bgColor;

/**
 *
 * @author faynch
 */
public class setting extends javax.swing.JFrame {
    Font font;
    static Color bgColor = Color.WHITE;
    static Color fgColor = Color.BLACK;
    /**
     * Creates new form setting
     */
    public setting() {
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, new File("Chewy-Regular.ttf")).deriveFont(20f);
            GraphicsEnvironment g = GraphicsEnvironment.getLocalGraphicsEnvironment();
            g.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("Chewy-Regular.ttf")));
        }
        catch(IOException | FontFormatException e){
            
        }
        initComponents();
        getContentPane().setBackground(bgColor);
        
        if (bgColor == Color.WHITE) {lightM.setSelected(true);}
        else {darkM.setSelected(true);}
    }

    public static void updateTheme() {
        backgroundL.setForeground(fgColor);
        darkM.setBackground(bgColor);
        darkM.setForeground(fgColor);
        lightM.setBackground(bgColor);
        lightM.setForeground(fgColor);
        OkSettingB.setBackground(bgColor);
        OkSettingB.setForeground(fgColor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroudG = new javax.swing.ButtonGroup();
        backgroundL = new javax.swing.JLabel();
        darkM = new javax.swing.JRadioButton();
        lightM = new javax.swing.JRadioButton();
        OkSettingB = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        backgroundL.setFont(font);
        backgroundL.setText("Background");

        darkM.setBackground(new java.awt.Color(255, 255, 255));
        backgroudG.add(darkM);
        darkM.setFont(font);
        darkM.setText("Dark Mode");
        darkM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkMActionPerformed(evt);
            }
        });
        darkM.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                darkMPropertyChange(evt);
            }
        });

        lightM.setBackground(new java.awt.Color(255, 255, 255));
        backgroudG.add(lightM);
        lightM.setFont(font);
        lightM.setText("Light Mode");
        lightM.setToolTipText("");
        lightM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightMActionPerformed(evt);
            }
        });

        OkSettingB.setFont(font);
        OkSettingB.setText("OK");
        OkSettingB.setAlignmentY(0.0F);
        OkSettingB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkSettingBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(darkM)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lightM)
                                .addGap(18, 18, 18)
                                .addComponent(OkSettingB, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backgroundL)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backgroundL, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(darkM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lightM)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OkSettingB)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void darkMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkMActionPerformed
        // TODO add your handling code here:
        bgColor = Color.BLACK;
        fgColor = Color.WHITE;
        darkM.setSelected(true);
        
    }//GEN-LAST:event_darkMActionPerformed

    private void darkMPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_darkMPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_darkMPropertyChange

    private void OkSettingBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkSettingBActionPerformed
        // TODO add your handling code here:
        getContentPane().setBackground(bgColor);
        updateTheme();
        mainWindow.bgColor = bgColor;
        mainWindow.fgColor = fgColor;
        mainWindow.updateTheme();
        setVisible(false);
    }//GEN-LAST:event_OkSettingBActionPerformed

    private void lightMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightMActionPerformed
        // TODO add your handling code here:
        bgColor = Color.WHITE;
        fgColor = Color.BLACK;
        
    }//GEN-LAST:event_lightMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton OkSettingB;
    private javax.swing.ButtonGroup backgroudG;
    private static javax.swing.JLabel backgroundL;
    private static javax.swing.JRadioButton darkM;
    private static javax.swing.JRadioButton lightM;
    // End of variables declaration//GEN-END:variables

}
