/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_ui;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author faynch
 */
public class usinEvent extends javax.swing.JFrame {
    Font font;
    static Color bgColor;
    static Color fgColor;
    String task = "";
    
    /**
     * Creates new form usinEvent
     */
    public usinEvent() {
        
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, new File("Chewy-Regular.ttf")).deriveFont(20f);
            GraphicsEnvironment g = GraphicsEnvironment.getLocalGraphicsEnvironment();
            g.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("Chewy-Regular.ttf")));
        }
        catch(IOException | FontFormatException e){
            
        }
        
        initComponents();
        
        eventL.setFont(font.deriveFont(30f));
        warning.setFont(font.deriveFont(20f));
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usinEventP = new javax.swing.JPanel();
        okB = new javax.swing.JButton();
        eventL = new javax.swing.JLabel();
        dateL = new javax.swing.JLabel();
        dateSpin = new javax.swing.JSpinner();
        monthL = new javax.swing.JLabel();
        monthB = new javax.swing.JComboBox<>();
        taskL = new javax.swing.JLabel();
        taskE = new javax.swing.JTextField();
        warning = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        usinEventP.setBackground(new java.awt.Color(255, 255, 255));

        okB.setFont(font);
        okB.setText("OK");
        okB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBActionPerformed(evt);
            }
        });

        eventL.setFont(font);
        eventL.setText("EVENT");

        dateL.setFont(font);
        dateL.setText("Date");

        dateSpin.setFont(font);
        dateSpin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        dateSpin.setFocusable(false);

        monthL.setFont(font);
        monthL.setText("Month");

        monthB.setFont(font);
        monthB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Month-", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        taskL.setFont(font);
        taskL.setText("Task");

        taskE.setFont(font);

        warning.setFont(font);
        warning.setBorder(null);

        javax.swing.GroupLayout usinEventPLayout = new javax.swing.GroupLayout(usinEventP);
        usinEventP.setLayout(usinEventPLayout);
        usinEventPLayout.setHorizontalGroup(
            usinEventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usinEventPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usinEventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usinEventPLayout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addGroup(usinEventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usinEventPLayout.createSequentialGroup()
                                .addComponent(okB)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usinEventPLayout.createSequentialGroup()
                                .addGroup(usinEventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taskE, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taskL)
                                    .addGroup(usinEventPLayout.createSequentialGroup()
                                        .addComponent(dateL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(usinEventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(usinEventPLayout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(eventL))
                                            .addGroup(usinEventPLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(monthL)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(monthB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(24, 24, 24))))
                    .addComponent(warning, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        usinEventPLayout.setVerticalGroup(
            usinEventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usinEventPLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(eventL)
                .addGap(18, 18, 18)
                .addGroup(usinEventPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateL)
                    .addComponent(monthL)
                    .addComponent(monthB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(taskL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taskE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usinEventP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usinEventP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBActionPerformed
        // TODO add your handling code here:
        warning.setText("");
        task = String.format("%4d / %2d  :  %s", dateSpin.getValue(), monthB.getSelectedIndex(), taskE.getText());
        System.out.println(task);
        if (validEvent()) {
            memoForm.eventModel.addElement(task);
        }
        task = "";
    }//GEN-LAST:event_okBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usinEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usinEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usinEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usinEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usinEvent().setVisible(true);
            }
        });
    }
    
    public static void updateTheme() {
        usinEventP.setBackground(bgColor);
        okB.setBackground(bgColor);
        warning.setBackground(bgColor);
        
        eventL.setForeground(fgColor);
        dateL.setForeground(fgColor);
        monthL.setForeground(fgColor);
        taskL.setForeground(fgColor);
        okB.setForeground(fgColor);
        warning.setForeground(fgColor);
        
    }
    
    public static boolean validEvent() {
        boolean check = true;
        int[] monthOf30thList = {4,6,9,11};
        if (monthB.getSelectedIndex() == 0) {
            warning.setText("!!! Select Month !!!");
            check = false;
        }
        
        if (monthB.getSelectedIndex() == 2 && (Integer)dateSpin.getValue() > 28) {
            warning.setText("!!! Invalid Date !!!");
            check = false;
        }
        
        if (Arrays.asList(monthOf30thList).contains(monthB.getSelectedIndex()) && (Integer)dateSpin.getValue() > 30){
            warning.setText("!!! Invalid Date !!!");
            check = false;
        }
        
        if (taskE.getText().equals("")) {
            warning.setText("!!! Add Event !!!");
            check = false;
        }
        return check;   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel dateL;
    private static javax.swing.JSpinner dateSpin;
    private static javax.swing.JLabel eventL;
    private static javax.swing.JComboBox<String> monthB;
    private static javax.swing.JLabel monthL;
    private static javax.swing.JButton okB;
    private static javax.swing.JTextField taskE;
    private static javax.swing.JLabel taskL;
    private static javax.swing.JPanel usinEventP;
    private static javax.swing.JTextField warning;
    // End of variables declaration//GEN-END:variables
}
